[workspace]

members = [
    "app",
    "boids",
    "boids/examples/boids_example",  # I dont want this here
    "common",
    "util",
    "bucket",
    "forum",
    "auth",
    "header",
]
exclude = [
]

[profile.release]
#lto = true
#panic = 'abort'

[profile]
lto = true