[workspace]
members = [
    "backend/",
    "db_proc_macros/",
    "wire/",
    "identifiers"
]
exclude = [
    "frontend" # The frontend needs to be excluded because it can't compile some of the crates in the workspace context for wasm
]