[workspace]
members = [
    "backend/",
    "db_proc_macros/",
    "wire/"
]
exclude = [
    "frontend7" # The frontend needs to be excluded because it can't compile some of the crates in the workspace context for wasm
]