[package]
name = "error"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[dependencies]
rocket = "0.3.13"
warp = "0.1.9"

[dependencies.diesel]
version = "1.3.2"

[features]
default = []
rocket_support = []
warp_support = []
