[package]
name = "common_auth"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]

[dependencies]
serde_derive = "1.0.14"
serde = "1.0.14"
serde_json = "1.0.3"

chrono = { version = "0.4", features = ["serde"] }
frank_jwt = "3.0.0"
