[package]
name = "pool"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
r2d2-diesel = "1.0.0"
r2d2 = "*"

[dependencies.diesel]
version = "1.3.2"
features = ["postgres", "uuid", "chrono", "serde_json"]
